Maeloni lesson backend
edugator-cise/edugator-staff-backend pull request #126
Opened 2023-02-01 04:52 UTC by Mae830

Changed the controller for the module so that the lessons will be deleted as their corresponding lesson is deleted. This should only have a change in the module controller.

2023-02-01 17:53 UTC, kapooramanpreet commented
Hi Maeloni, Can you do a git pull from main into this branch and push the code again? I feel like there are a lot of files to review which should not be the case here.

2023-02-08 18:51 UTC, Mae830 commented
Hey yeah I can do that sorry for seeing this late


On Wed, Feb 1, 2023 at 12:54 PM Amanpreet Kapoor ***@***.***>
wrote:

> Hi Maeloni, Can you do a git pull from main into this branch and push the
> code again? I feel like there are a lot of files to review which should not
> be the case here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/edugator-cise/edugator-staff-backend/pull/126#issuecomment-1412482209>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANFIPDLMLCVJMXAVATXG5Y3WVKPLXANCNFSM6AAAAAAUNIAQCM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-14 02:18 UTC, marcgabe15 requested changes

2023-02-14 02:18 UTC, marcgabe15 commented on src/api/controllers/module.controller.ts
> +        for (let i = 0; i < module.problems.length; i++) {
module.lessons?

2023-02-14 05:09 UTC, Mae830 commented
Done. Tests now pass thank you for finding this

On Mon, Feb 13, 2023 at 9:18 PM Marc Diaz ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/api/controllers/module.controller.ts
> <https://github.com/edugator-cise/edugator-staff-backend/pull/126#discussion_r1105220651>
> :
>
> > @@ -236,6 +237,21 @@ export const deleteModule = async (
>          return;
>        }
>
> +      //Delete the lesson arrays
> +      try {
> +        for (let i = 0; i < module.problems.length; i++) {
>
> module.lessons?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/edugator-cise/edugator-staff-backend/pull/126#pullrequestreview-1296732757>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANFIPDKYP3GFLFJURBYJV6LWXLTOJANCNFSM6AAAAAAUNIAQCM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-02-14 15:04 UTC, kapooramanpreet requested changes
I thiunk Lin should also be module.lessons[i]

2023-02-23 15:18 UTC, kapooramanpreet approved these changes
Thanks for addressing the changes.

2023-02-23 15:44 UTC, digitdustin approved these changes

2023-02-23 15:56 UTC, kapooramanpreet commented
Added requested changes.

2023-02-23 15:56 UTC, merged