made changes to data types and responses
edugator-cise/edugator-staff-backend pull request #157
Opened 2023-07-20 00:31 UTC by prayujt

- Added `difficulty`, `author`, and `codeSolution` fields to problems.
- Changed getProblem to not return test case info in student call
- Moved language specification to courses instead of problems

2023-07-21 18:39 UTC, kapooramanpreet requested changes

2023-07-21 18:39 UTC, kapooramanpreet commented on src/api/dal/problem.ts
> +    args['order'] = [['testCases', 'orderNumber', 'ASC']];
do we also include solution here?

2023-07-22 03:38 UTC, prayujt commented on src/api/models/v2/problem.model.ts
> +  author: string;
planetscale automatically includes the `dateCreated` and `dateModified` properties - assuming we stick with planetscale we don't need to handle that on our end and it is returned when retrieving the problem/lesson

2023-07-22 04:30 UTC, digitdustin submitted a review, later dismissed

2023-07-22 13:02 UTC, kapooramanpreet submitted a review, later dismissed
LG!

2023-07-27 01:01 UTC, kapooramanpreet approved these changes
LG!

2023-07-28 00:17 UTC, marcgabe15 approved these changes

2023-07-28 00:19 UTC, merged

2023-07-28 19:43 UTC, kapooramanpreet reviewed
LG